### PR TITLE
Explain me how this is better than IRC.

### PR DESCRIPTION
**Pull request by funkaoshi**
[HackerNews suggests a better title for the first block of the project website.][1]

Please upboat my pull request.

[1]: https://news.ycombinator.com/item?id=9027444

### CODE REVIEW

**Comment by hhaidar** [comment]
qoutes pls

**Comment by funkaoshi** [comment]
I've added a link to the quote.

**Comment by sibartlett** [comment]
:boat: :boat: :boat: :boat: :boat: :boat: :boat: :boat: :boat: :boat: :boat: :boat:

**Comment by hhaidar** [comment]
explain me how this ok real life

**Comment by notsrg** [comment]
+1 if it works

**Comment by emintham** [comment]
:up: :boat:

**Comment by hhaidar** [comment]
but does it work in Tesla P85?

**Comment by funkaoshi** [comment]
@notsrg I haven't actually ran it. I just edited the HTML in the github in-browser editor.

**Comment by sibartlett** [comment]
@hhaidar why would I use a Tesla P85 rather than IRC?

**Comment by blakecrosby** [comment]
:+1:

**Comment by geoffwhittington** [comment]
:+1:

**Comment by hhaidar** [comment]
:ok_hand:

**Comment by funkaoshi** [comment]
@hhaidar feel free to merge at your discretion.

**Comment by hhaidar** [comment]
Haha, we like to make funnies sometimes.

**Pull request closed without merging**
