### PR TITLE
Create room if user join unknown room

### PR DESCRIPTION
**Pull request by manland**
Follow xmpp spec http://xmpp.org/extensions/xep-0045.html#createroom

### CODE REVIEW

**Comment by sibartlett** [comment]
Awesome stuff! Thank you :smile:

**Comment by manland** [comment]
Thanks ! I'm on private-room #198 now, but it seems more complicated :hurtrealbad: :smiley:

**Comment by hhaidar** [comment]
You're a legend @manland

**Comment by sibartlett** [comment]
@manland see my latest commit, you can define extra methods in the extend method now.

Also for us to merge passworded rooms in, we'd need the same functionality in both the XMPP and web interfaces. We might be able to help there though.

**Comment by manland** [comment]
@hhaidar thanks :sweat_smile: :flushed: 

@sibartlett thanks for the tips, i will take a look on your last commit. For the passworded rooms i have listed web client, xmpp and rest api :innocent:

**Comment by sibartlett** [comment]
@manland I've disabled this functionality by default, but it can be enabled via configuration. Please see this commit: ccbe1a0304498789723509f58ecd9a8135f03728

**Pull request merged**
