### PR TITLE
Include headers in authentication methods 

### PR DESCRIPTION
**Pull request by Schniz**
used for [lets-chat-reverseproxy](https://github.com/Schniz/lets-chat-reverseproxy)

there are some organizations that use Kerberos or some authentication via SSO headers (`REMOTE_USER`, `X-Remote-User` and so on).
the `passport-reverseproxy` came to the rescue, but the `req` object in `app/auth/index.js` only sends the `user` and `password`. for `reverseproxy` it should also send the `headers` so we could authenticate the user.

plus, if we will make it happen, users won't have to actively sign in in organizations with SSO headers. auto login for the win.
but the auto login is not implemented here yet.
maybe the app should let the plugins to authenticate automatically the users?

### CODE REVIEW

**Comment by geoffwhittington** [comment]
This is great @Schniz ! I'll see if I can get this working on my install.

Other possible names might be 'headerauth' or 'trustedauth'.

In the future if we support more plugins I think we'll want to clarify the names. I.e. this might become 'lets-chat-auth-reverseproxy'. Given the current code your naming scheme is right

**Comment by Schniz** [comment]
@geoffwhittington seems legit. when you guys would like to change the name you can tell me and I do so or you can just fork it.
Its based on the kerberos plugin :stuck_out_tongue:

**Comment by hhaidar** [comment]
+1

**Comment by sibartlett** [comment]
This can't be merged as-is, it'll break XMPP.

**Comment by geoffwhittington** [comment]
We should update the wiki if reverse proxy is a new auth thing we can support

**Comment by sibartlett** [comment]
@Schniz can you try the latest code on master? Could you also amend your README with the following?

* adding that reverse proxy is not supported for XMPP
* and removing the Node 0.10 part

**Comment by Schniz** [comment]
:+1:  I'll test it this week
thanks for the inputs!

XMPP does not have headers? which XMPP client you guys use to test the app?

**Pull request closed without merging**
