### PR TITLE
Allow dot in username

### PR DESCRIPTION
**Pull request by scragg0x**
We have dots in our usernames.  We need the dots.

### CODE REVIEW

**Comment by hhaidar** [comment]
Seems reasonable, thanks!

**Comment by hhaidar** [comment]
Actually sorry, this might affect XMPP/Jabber. Do  you mind reopening?

**Comment by scragg0x** [comment]
According to http://xmpp.org/extensions/xep-0029.html#sect-idp666800 the period is valid for jabber ids.

**Comment by sibartlett** [comment]
I'll get this merged in over the weekend.

**Comment by sibartlett** [comment]
One issue by introducing dots in usernames, is that it impacts mentions. It'll require a little more thought.

**Comment by hhaidar** [comment]
@scragg0x merged in via #238 and mentions should work too!

**Comment by sibartlett** [comment]
@hhaidar nice work!

**Comment by hhaidar** [comment]
@sibartlett lol u.

**Pull request merged**
