### PR TITLE
Docker: Enable XMPP port support

### PR DESCRIPTION
**Pull request by pulser**
The dockerfile and fig config don't currently forward port 5222.
This patch exposes port 5222 from the Dockerfile, and forwards it
in the fig configuration, meaning users can enable XMPP in settings.

### CODE REVIEW

**Comment by hhaidar** [comment]
This seems good. @geoffwhittington?

**Comment by pulser** [comment]
FYI I am now using this in "deployment" via docker, with this patch, and it seems fine. SSL works over port 5222 as well with no other changes, which is nice. 

This makes it easy to test out XMPP support quickly though when developing.

**Comment by sibartlett** [comment]
This only opens the port. XMPP should probably be enabled in Let's Chat via ENV - if we want to merge this?

**Comment by hhaidar** [comment]
@pulser @sibartlett ya can one of you do that? Minor blocker, let's get this thing merged.

**Comment by vwbusguy** [comment]
For what it's worth, adding XMPP by the settings file does not work for either docker-compose or the traditional build/run, even with exposing and forwarding these ports.  It works perfectly by passing the directives via --env-file file though.

**Comment by vwbusguy** [comment]
The other concern about enabling XMPP by default would be generating a key for encryption or disabling the default encryption.  For actual deployment, the key should be added with a proper ADD in the Dockerfile, but for initial development it should otherwise be fine.

**Comment by pulser** [comment]
@hhaidar

My approach in setting this up was to make my "own" settings.yml file, which contained the appropriate settings. This enables XMPP, and enables XMPP with TLS, setting the filename of the certificate etc.

Using this patch in the fig.yml file, it invokes the Dockerfile "onbuild" which builds the app up. That process "pulls in" the settings.yml configuration, thus enabling XMPP.

I've not used environmental variables to control Let's Chat, but I see the docs in the wiki which explain it. I will add the one to enable XMPP in fig.yml. I won't add a key/certificate, but I suppose we could add commented-out lines to fig.yml to show how to enable TLS and keys?

I guess this just depends on your preferred way to configure Let's Chat - for me, it was just to edit settings.yml, but I see how some may prefer to use fig.yml to set ENV variables. I will attempt to amend this PR.

**Comment by pulser** [comment]
Seems I managed to break this PR.

**Comment by vwbusguy** [comment]
@pulser , but why close it?  This still seems like a very useful feature.  Though, I admit that having these set in a settings.yaml would have been nice, controlling them by env-file ended up working just fine and is probably more appropriate in a production setting.  Either way, since the Docker will likely be many's first experience with lets-chat, having XMPP out of box would be very helpful for evaluation.

**Comment by pulser** [comment]
@vwbusguy - indeed, I will re-submit it (just real life took over sadly). Thanks for reminding me. I totally agree - docker is a great way to deploy things like this.

I will set about doing it properly this time from a feature branch, and put that up for review shortly as a PR in itself.

**Pull request closed without merging**
