### PR TITLE
Fixed typo which causes vagrant not to run

### LINKED ISSUE #200: Typo in Vagrantfile causes Vagrant not to run.
Hi guys,

I'm brand new to this project but a friend told me about it and I thought I would check it out. So I cloned the repository and tried to get it to run as per the instructions but I was immediately hit with this issue. This error causes vagrant not to create the vm because it cannot properly run the provisioning script.

```
$ vagrant up
Bringing machine 'lcb' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* One of `path` or `inline` must be set.
```

### PR DESCRIPTION
**Pull request by azend**
Fixes #200 by removing the dollar sign.

### CODE REVIEW

**Comment by sibartlett** [comment]
Woops, that was embarrassing - thank you for finding and fixing this! :smile:

**Comment by sibartlett** [comment]
I'm also going to update the vagrant file to run the database migration scripts automatically.

**Comment by azend** [comment]
Thanks for responding so quickly! :)

**Comment by geoffwhittington** [comment]
What version were you testing against @azend? I built this using Vagrant on Windows.

**Comment by azend** [comment]
@geoffwhittington I built this repo based off of the master branch running on Mac OSX 10.9.5 using Vagrant 1.7.2

Seems to build fine from:  https://github.com/sdelements/lets-chat/commit/09e131328dab3b0377ff66e16ab6e442c835eb65

**Pull request merged**
