### PR TITLE
Audio notification when someone mentions a user

### PR DESCRIPTION
**Pull request by vivek27**
A ping sound when someone mentions a user in one of the rooms he/she is present.
 
The coding standard has been replicated from raptorize in media/js/vendors where static audio files are stored.

### CODE REVIEW

**Comment by vivek27** [comment]
https://www.npmjs.com/package/sfx could be used in place of using HTML DOMs to achieve the same. This package comes with pre-built sounds which we can use directly like:

var sfx = require('sfx');
sfx.ping();

But I couldn't find a way to use require() function inside /media/js/vendor/notifications/desktop_notifications.js.

**Comment by vivek27** [comment]
https://www.npmjs.com/package/sfx could be used in place of using HTML DOMs for sound notifications. This package comes with pre-built sounds which we can use directly like:

var sfx = require('sfx');
sfx.ping();

But I couldn't find a way to use require() function inside /media/js/vendor/notifications/desktop_notifications.js.

**Comment by hhaidar** [comment]
@vivek27 ideally the code for this shouldn't be in a vendor file.

Also we can't merge this into master without a toggle of some type.

**Comment by hhaidar** [comment]
Closing this for now. Definitely create an updated new one if possible @vivek27!

**Pull request closed without merging**
