### PR TITLE
Add allowed html to message formatting

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by fmarco** [comment]
LVTM

**Comment by hhaidar** [comment]
Sorry, this is not the type of usability we're going for :(

How about something using a subset of Markdown to do this kind of thing?

**Comment by funkaoshi** [comment]
Line breaks will be tricky with Markdown, I think. I agree it probably is tidier to post process "*" and "_" than escaped HTML.

**Comment by hhaidar** [comment]
If you send plaintext with `\n`, let's chat will render it.

**Comment by funkaoshi** [comment]
Ah yes, of course. Hah.

**Comment by astagi** [comment]
I just wanted to have a better layout using API to implement this https://github.com/taigaio/taiga-front/issues/359

Markdown is ok for me, I can work on it if you want and replace markdown with html and use format:'markdown'. Let me know.

**Comment by funkaoshi** [comment]
There is a tiny bit of discussion in #79 about Markdown.

**Comment by hhaidar** [comment]
@astagi +1, thanks for doing this :D

One small thing: message.format should be blank by default imo

**Comment by astagi** [comment]
no problem @hhaidar , @funkaoshi thank you for the link

here it is a new PR https://github.com/sdelements/lets-chat/pull/308

**Pull request closed without merging**
