### PR TITLE
authenticate users before allowing local auth password changes

### PR DESCRIPTION
**Pull request by geoffwhittington**

### CODE REVIEW

**Comment by hhaidar** [comment]
:+1:

**Comment by sibartlett** [comment]
:-1:

**Comment by hhaidar** [comment]
@sibartlett woops, you're right dude!

**Comment by geoffwhittington** [comment]
That's pretty funny guys. Thanks for the fix guys!

**Comment by hhaidar** [comment]
No worries, if Mr. Bartlett approves we merge.

Confirm check can happen on the frontend.

**Pull request merged**
