### PR TITLE
Send back a user profile in messages, even if user is not there

### PR DESCRIPTION
**Pull request by hhaidar**
Ref #400

### CODE REVIEW

**Comment by sibartlett** [comment]
Merged

**Comment by hhaidar** [comment]
@geoffwhittington what do you mean?

**Comment by geoffwhittington** [comment]
I expected "Unknown" was going to show up as the display name for room messages associated with deleted users. If I was German, Dutch, etc. I would prefer a different text which matched my mother tongue.

**Comment by hhaidar** [comment]
@geoffwhittington you're absolutely right. Something to worry about if we ever add for realsies i18n though :D

**Comment by geoffwhittington** [comment]
I guess there is a workaround though - fix the corrupted data! :wink:

**Pull request closed without merging**
