### PR TITLE
i18n

### PR DESCRIPTION
**Pull request by hhaidar**
Ref #466
Ref #69

### CODE REVIEW

**Comment by tonghuix** [comment]
Awesome!
Please Merge it, and open a project at Transifex!

**Comment by hhaidar** [comment]
Special thanks to @emintham for the quick simplified chinese translation

**Comment by hhaidar** [comment]
@tonghuix this is going into the develop branch, which is for release 0.4.0

It might be a while before it goes into master.

**Comment by hhaidar** [comment]
@tonghuix do you mind submitting a PR against the `i18n1` branch?

**Comment by tonghuix** [comment]
I give a quick review of this Simplified Chinese translation, and make some modification

Ooops, it seems I should give a pull request when this commit merged .

**Comment by sibartlett** [comment]
I updated `zh.json` with changes from @tonghuix.

**Comment by sibartlett** [comment]
@hhaidar I'm good with this being merged into develop.

**Comment by hhaidar** [comment]
@sibartlett cool, we still need to translate the js/server responses.

I'll merge this and we can open another PR to do that.

Maybe we can release 0.4.0 with what we have, and do whispers/marionette for 0.5.0

**Pull request merged**
