### PR TITLE
Add a host setting

### PR DESCRIPTION
**Pull request by hhaidar**
Ref #247

### CODE REVIEW

**Comment by hhaidar** [comment]
@sibartlett will docker and vagrant be affected if we use localhost?

I'm 50/50 on this thing right now.

**Comment by hhaidar** [comment]
Spoke to @sibartlett about this, it's probably better to just leave it undefined for the time being.

**Comment by geoffwhittington** [comment]
Vagrant should be ok with localhost I believe - the way stuff works now there is a port redirection on the host to the guest on port 5000.

**Comment by hhaidar** [comment]
@geoffwhittington do you mind updating defaults.yml in a branch and trying to deploy?

**Comment by funkaoshi** [comment]
I would have voted for localhost as well. (We shouldn't serve stuff up to everyone by default.)

**Pull request merged**
