### PR TITLE
Add compatibility with openshift for hosting

### PR DESCRIPTION
**Pull request by maxired**
Hi,

I use lets chat on OpenShift.
Since there is already compatibility with Heroku, you might be interested in this.

### CODE REVIEW

**Comment by sibartlett** [comment]
Thank you! :smile:

**Comment by tvvocold** [comment]
nice! thx!

**Comment by sibartlett** [comment]
@maxired quick question; for Let's Chat 0.2 you guys used:

```
process.env.OPENSHIFT_MONGODB_DB_URL + process.env.OPENSHIFT_APP_NAME
```

But now only use:

```
process.env.OPENSHIFT_MONGODB_DB_URL
```

This is correct?

**Comment by maxired** [comment]
Nice Catch.

This lead in using the default 'admin' database in Mongo, instead of using
the dedicated database of the application.
Everyhting is working fine on the Openshift Instance on which I am working
, but this can lead in lost of data in case of upgrading from previous
version.

**Comment by sibartlett** [comment]
I'll update it, and append the app name.

**Pull request merged**
