### PR TITLE
Private 1-to-1 chat

### PR DESCRIPTION
**Pull request by sibartlett**
Implemented for both API and XMPP.

When logged into XMPP, you'll see other users in your friend list - but only those connected via XMPP (until we implement the web interface).

Web client does not currently support this functionality.

#282

### CODE REVIEW

**Comment by hhaidar** [comment]
hello dreams, we meet again.

**Comment by kevindelaney** [comment]
👍

**Comment by funkaoshi** [comment]
Epic. People are going to lose their shit.

**Comment by fernandomoraes** [comment]
like

**Comment by geoffwhittington** [comment]
Great work @sibartlett ! You're on fire

It looks like the initial plan is to log all 1-1 messages like we do with room messages. In this case #68 will be very important for certain people. I'm assuming transcripts are secured, i.e. Bob cannot access the 1-1 messages of Sue, unless he is a participant.

Here are some considerations with respect to logging 1-1 messages:

For:
 - Allows for continuity of discussion (web-to-mobile)
 - Enables historical review
 - Enables Monitoring
 - A lot of people expect it
 - Some laws require companies to have it

Against:
 - Breaks the literal meaning of 1-1/private messaging.
 - Enables monitoring
 - People will wrongly assume server takes extra measures to keep the information private
 - Identical functionality already exists: rooms / passwords w/ transcripts

I personally don't like the idea of logging private messages. I'd rather not have it. However, we can avoid support for logging if we also accept the real risk a project fork, precisely due to the last point above - some companies are required by law to log.

I suggest we add an indicator that all messages are not private. Also to revisit this again where we can let people opt-out of logging 1-1 messages, at the server level, and allow automatic purge after a period of time

**Comment by sammcj** [comment]
Great :)

**Comment by sibartlett** [comment]
@geoffwhittington my current vision is this:

* 1-to-1 chats will be persisted by default
 * improved usability (especially with continuity between devices)
* Privacy can be obtained using OTR
 * We'll add support to the web interface, using [this library](https://github.com/arlolra/otr)
 * OTR is supported over the XMPP protocol with no work needed from us
 * Let's Chat recognizes OTR messages, and does not store them in the database

**Comment by hsitaa** [comment]
hello, kinda confused!  is the feature now available for web client or yet not available ? 
coz 
https://github.com/sdelements/lets-chat/blob/develop/defaults.yml
doesn't include any such config parameter . and by default clicking on people logged in 1-1 chat doesn't work
Kindly guide if i am missing something. because this is a great feature do not want to miss if it has already been implemented.

**Comment by sibartlett** [comment]
@hsitaa this feature has so far only been implemented for users logged in via XMPP

**Comment by rockneverdies55** [comment]
:+1: Excited to see this implemented for web clients too.

**Pull request merged**
