### PR TITLE
Password-Protected Rooms

### PR DESCRIPTION
**Pull request by sibartlett**
This pull request supersedes #257.

Still a WIP - DO NOT MERGE!

I plan to generalize a few things before this is merged, so that we can extend this functionality further (in a future pull request) to include invites, roles etc.

Require configuration:

```yml
rooms:
  passwordProtected: true
```

### CODE REVIEW

**Comment by geoffwhittington** [comment]
Looks great! A few notes:

- I had trouble getting the new password field to show up until I updated the settings `rooms.passworded: true`
- Can we do better than using `passworded` as a name?
- I can't seem to edit rooms (no button) created before testing this PR
- Need a password confirm field for room creation
- Dialog box says "Are you sure?, Users can share this password with other users (who were not invited by you)." What do we think of something like, "You are about to created a password-protected room. Keep it safe! You can change the password later if you think unauthorized users may join".
- Changing the password doesn't lockout people in the room. i.e. once they're in the room they are in there for good. Presume it affects any new people
- Editing a room with a password requires a password
    - Should have a confirm password field
    - Should allow people to update the room name/desc without changing the password. It doesn't currently

**Comment by manland** [comment]
Cool, let me know if I can help ;)

**Comment by geoffwhittington** [comment]
Don't forget we want to merge into develop now, hopefully that doesn't mess things up

**Comment by sibartlett** [comment]
This has been merged into develop.

The modal message still needs to be updated, but that can be done on develop.

**Pull request closed without merging**
