### PR TITLE
Added link to azure storage plugin

### PR DESCRIPTION
**Pull request by maximilian-krauss**
I added a link to my Azure storage plugin to your README file.

I wasn't sure where the best place would be to place that link, so I added it to the list of available file uploads. Alternatively we could create an 3rd party section for all plugins which were not developed by you or something like that ...

### CODE REVIEW

**Comment by hhaidar** [comment]
This is cool, I've added it to the wiki too https://github.com/sdelements/lets-chat/wiki/Files

**Comment by maximilian-krauss** [comment]
Great, thanks :+1:

**Comment by sibartlett** [comment]
I also added a plugins page to the wiki last weekend: https://github.com/sdelements/lets-chat/wiki/Plugins

**Comment by hhaidar** [comment]
@sibartlett ah, forgot about that!

**Pull request merged**
