### PR TITLE
private rooms (1:1 and many to many)

### PR DESCRIPTION
**Pull request by szels**
Hey guys,

we at uberall.com used our internal hackathon last friday to implement the private rooms feature.
For our daily work we're using grails but for the hackday we tried node. So, please be gentle. ;)
We know this is not ready for production. But at least it worked for our hackday team with 3 members.

In the 'add room' and 'edit room' view you can type in the names of users who are allowed to see and to use the room. Private rooms are not visible to non members.

Feedback is welcome :)

### CODE REVIEW

**Comment by kemenaran** [comment]
Wow, that'd be great!

**Comment by hhaidar** [comment]
Wow this looks awesome!

**Comment by WhiteHatTux** [comment]
Look quite nice. :-) I created a private room and with another user tried to create the same room again and got a message saying "Unable to create room Room slugs can only contain lower case letters, numbers or underscores!"

Maybe a more verbose message could be put here.

**Comment by sibartlett** [comment]
@hhaidar this was the pull request that I was tidying up the other day, will show you it when I'm back.

**Comment by geoffwhittington** [comment]
My question is who gets the :beers:

**Comment by muddydixon** [comment]
That's good. Please merge this!!!

**Comment by sibartlett** [comment]
Closing this pull request. I've opened a new pull request (#449) that addresses editing room participants. Thanks for submitting this pull request, I used some of the your ideas in the new pull request.

**Pull request closed without merging**
