### PR TITLE
load login page after successful registration

### PR DESCRIPTION
**Pull request by geoffwhittington**

### CODE REVIEW

**Comment by geoffwhittington** [comment]
This is a possible solution for #181

**Comment by geoffwhittington** [comment]
1 second might be too short a time to see registration is successful. A button to login is a better solution

**Comment by hhaidar** [comment]
Sure, lemme add that with swal

**Comment by hhaidar** [comment]
Btw you don't get a session after registration right now...

... and hiding sweetalert's button during success also hides the button for registration

**Comment by geoffwhittington** [comment]
The "login" button after registration you added is awesome! Better than my solution - I'm closing this PR and deleting the branch

**Pull request closed without merging**
