### PR TITLE
SSL image proxy

### LINKED ISSUE #354: Only allow HTTPS links in the web chat to ensure no mixed content is shown in the web chat
I got mixed content errors in chrome because I copied a HTTP link which is rendered in the chat itself and thus provides mixed content of HTTP and HTTPS.
Please make it possible to only allow external HTTPS links so there are nog mixed content warning.

### PR DESCRIPTION
**Pull request by maximilian-krauss**
Fixes #354 

This PR adds an image proxy for inline images which are referenced over HTTP. This only happens if the lets-chat instance is served over HTTPS and the sslImageProxy setting (see below) is set to `true`.

### Configuration
Path | default | Environment Variable
--- | --- | ---
`rooms.sslImageProxy` | `false` | `LCB_ROOMS_SSLIMAGEPROXY`

### CODE REVIEW

**Comment by hhaidar** [comment]
great job!

**Comment by maximilian-krauss** [comment]
Hi @hhaidar,
is there any chance to get this one merged in the near future?
I plan to upgrade our lets-chat instance at work to 0.4 and it would be awsome if I could minimze the merge effort :smile:

**Comment by hhaidar** [comment]
I'm good with this, if @sibartlett is on board let's merge!

**Comment by maximilian-krauss** [comment]
@sibartlett @hhaidar \*poke\* :wink:

**Comment by hhaidar** [comment]
@maximilian-krauss I'm so sorry this is taking forever to get in, I'll try and make it go into 0.4.3 (we're testing it on our instance)

**Pull request closed without merging**
