### PR TITLE
Release/0.3.0

### PR DESCRIPTION
**Pull request by funkaoshi**
This is @hhaidar's release plan: 

 - [x] New flexbox layout
 - [x] Updated libs
 - [x] Gruntfile
 - [x] Passport / LDAP
 - [x] XMPP #99
 - [x] Auth tokens
 - [x] Auth token UI
 - [x] Disable local auth
 - [x] HTTPS
 - [x] Message Rendering
 - [x] Room History
 - [x] Room Creation
 - [x] Room Editing
 - [x] Room Archival
 - [x] Rooms API
 - [x] Messages API
 - [x] Account API
 - [x] Users API
 - [x] File Uploads #123
 - [x] S3 File Storage
 - [x] User List Population (we have the endpoints for this)
 - [x] Heroku
 - [x] Environment variable settings
 - [x] Account/Profile endpoints
 - [x] Notifications can open room #101
 - [x] Mention badges
 - [x] Emotes
 - [x] Install docs (local, Heroku, Docker, Vagrant)
 - [x] Upgrade docs
 - [x] XMPP docs
 - [x] LDAP docs
 - [x] API docs
 - [x] Better message formatting
 - [x] Open rooms in localstorage
 - [x] Keyboard Shortcuts
 - [x] Focus input on room switch
 - [x] Firefox message layout breaks #44
 - [x] Database migrations? [Migroose](https://github.com/derickbailey/migroose)?
 - [x] Add check for database integrity before running migrations
 - [x] Remove references to "release/0.3.0" branch from README, Dockerfile, Vagrantfile #134

### CODE REVIEW

**Comment by funkaoshi** [comment]
Are we just going to call this 1.0?

**Comment by geoffwhittington** [comment]
This release plan list keeps growing. Is this a bug?

**Comment by hhaidar** [comment]
We've deployed this internally.

This is the last mile. It's been real people. Too real.

**Comment by funkaoshi** [comment]
We have all the docs we want right now, it seems.

What's the notification problem that is still marked as TODO?

We should add TODOs for the migration updates?

**Comment by sibartlett** [comment]
I've marked the documentation has DONE. The documentation still needs improvement, but it's not a blocker for merging into master.

I've added a TODO for the migration fix/update.

Before merging, I also would like to review the format of our LDAP configuration settings:

* to check that they'll be easy to extend if we need to add more options in the future
* to reduce the length of the associated [env vars](https://github.com/sdelements/lets-chat/wiki/Environment-variables)

**Comment by sibartlett** [comment]
I've started organizing the GitHub issues into a roadmap using milestones.

The 0.3 milestone is here: https://github.com/sdelements/lets-chat/milestones/0.3

I'm still undecided whether we should close issues that have been raised by external users now, or keep them open until we merge into master. Technically it's not fixed for them until it's merged into master, but keeping them open makes the milestone more noisy.

**Comment by hhaidar** [comment]
I'd keep them open for now.

**Comment by funkaoshi** [comment]
Going forward we should probably think about having master track development work, and we tag what we want to call 0.3, 0.4, etc. Then we go back to just having small feature branches.

**Comment by sibartlett** [comment]
Maybe we should have a develop branch? We definitely should still tag releases though.

**Comment by funkaoshi** [comment]
@sibartlett might want to a production branch, and master is the development branch? Or yeah, do it the same way we do SDE, where master is always deployable/production.

**Comment by funkaoshi** [comment]
I can't believe this branch is done.

**Comment by hhaidar** [comment]
Master should be stable. I'm cool with either a release/x or develop branch.

**Comment by hhaidar** [comment]
@funkaoshi ya its epic! I remember when we worked on it at your place last summer.

**Comment by almereyda** [comment]
Kidding me?! Congratulations. :cocktail:

**Pull request merged**
