### PR TITLE
File Uploads (WIP)

### PR DESCRIPTION
**Pull request by hhaidar**

### CODE REVIEW

**Comment by hhaidar** [comment]
Okay this is pretty much ready to go in. We just need to figure out how we're going to do pasted links/embeds.

Some of the plugin styling is a little ugly too...

**Comment by hhaidar** [comment]
screen shot 2015-02-06 at 2 13 25 am

**Comment by sibartlett** [comment]
Error: template not found: includes/js/file.html

**Comment by hhaidar** [comment]
Sorry, try now!

**Comment by sibartlett** [comment]
Very nice!

We also need to hide and disable all the file stuff on the client, if files are disabled in settings.yml

**Pull request merged**
