### PR TITLE
Show unread mentions as favicon badge

### PR DESCRIPTION
**Pull request by lumeet**
The same way as the document title for an inactive window is updated
to show new messages and mentions, favicon is changed to show new
mentions only.

I find the behavior extremely useful when the chat window is behind a pinned tab. So, the feature itself would be great to have even if you prefer some other solution. [Favico.js](http://lab.ejci.net/favico.js/) is the library used here.

### CODE REVIEW

**Comment by WhiteHatTux** [comment]
I tried it out and as far as i can tell it works quite nicely. Maybe there is an easy way to introducing a slightly changed favicon, when there is new messages. Might be a stronger indication, then the change, that is already shown by the browser.

**Comment by sibartlett** [comment]
We were also thinking that we might want the favicon to alternative between the two different counts (unread messages and unread mentions). Each count would be displayed using different colours?

**Comment by WhiteHatTux** [comment]
I'd vote for blue as unread and red as mentioned. 
But the icon will probably not allow 2 counts. Maybe a blue one if there is just messages and a red one if there is a mention. Maybe a mention would overwrite normal messages?

**Comment by sibartlett** [comment]
I was thinking we'd switch between them using a timer.

**Comment by hhaidar** [comment]
I love this thing

**Comment by lumeet** [comment]
Thanks, I pushed a new commit based on the ideas by @WhiteHatTux and @sibartlett.

**Comment by WhiteHatTux** [comment]
And that's also working quite well. Two things though. (Taking into account, that this is only personal taste)
1. I would set the timer to the same value as the window switch so it's possible to catch it with a quick look.
2. I would still go with blue (maybe something like #1414ff) for unread messages as red appears to me as an alarming color whereas a message in a chat room is usually not "alarming" 

Either way. It looks great and i would love to see that "live" soon.

**Comment by hhaidar** [comment]
We can merge this thing in as is, thanks @lumeet <3

**Pull request merged**
